In [20]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf

In [25]:
olist = pd.read_csv('/Users/adelaelezaj/Desktop/brazilian-ecommerce/olist_table.csv')

In [26]:
olist.head(10)

,customer_unique_id,first_order,year,month,after_6mth,number_of_orders,total_payment,avg_payments,customer_state,avg_score
0,8d50f5eadf50201ccdcedfb9e2ac8455,2017-05-15,2017,5,2017-11-15,17,927.63,55,SP,4.76
1,3e43e6105506432c953e165fb2acf44c,2017-09-18,2017,9,2018-03-18,9,1172.66,130,SP,2.78
2,1b6c7548a2a1f9037c1fd3ddfed95f33,2017-11-13,2017,11,2018-05-13,7,959.01,120,MG,5.00
3,6469f99c1f9dfae7733b25662e7f1782,2017-09-19,2017,9,2018-03-19,7,758.83,108,SP,5.00
4,ca77025e7201e3b30c44b472ff346268,2017-10-09,2017,10,2018-04-09,7,1122.72,160,PE,5.00
5,12f5d6e1cbf93dafd9dcc19095df0b3d,2017-01-05,2017,1,2017-07-05,6,110.72,18,PR,5.00
6,47c1a3033b8b77b3ab6e109eb4d5fdf3,2017-08-07,2017,8,2018-02-07,6,997.32,142,SP,4.86
7,63cfc61cee11cbe306bff5857d00bfe4,2017-05-11,2017,5,2017-11-11,6,826.32,138,RJ,4.50
8,dc813062e0fc23409cd255f7f53c7074,2017-07-01,2017,7,2018-01-01,6,1094.63,182,PE,4.50
9,de34b16117594161a6a89c50b289d35a,2017-11-03,2017,11,2018-05-03,6,660.94,110,SP,3.00

In [27]:
olist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96135 entries, 0 to 96134
Data columns (total 10 columns):
customer_unique_id    96135 non-null object
first_order           96135 non-null object
year                  96135 non-null int64
month                 96135 non-null int64
after_6mth            96135 non-null object
number_of_orders      96135 non-null int64
total_payment         96135 non-null float64
avg_payments          96135 non-null int64
customer_state        96135 non-null object
avg_score             96135 non-null float64
dtypes: float64(2), int64(4), object(4)
memory usage: 7.3+ MB

In [29]:
olist.describe()

,year,month,number_of_orders,total_payment,avg_payments,avg_score
count,96135.000000,96135.000000,96135.000000,96135.000000,96135.000000,96135.000000
mean,2017.538253,6.031466,1.034379,167.107862,158.714818,4.069623
std,0.505293,3.233385,0.213143,232.745894,219.487419,1.353536
min,2016.000000,1.000000,1.000000,0.000000,0.000000,1.000000
25%,2017.000000,3.000000,1.000000,63.100000,61.000000,4.000000
50%,2018.000000,6.000000,1.000000,108.000000,104.000000,5.000000
75%,2018.000000,8.000000,1.000000,183.890000,175.000000,5.000000
max,2018.000000,12.000000,17.000000,13664.080000,13664.000000,5.000000

In [35]:
formula = 'total_payment ~ C(customer_state) + C(avg_score)'

fitted_model = smf.ols(formula=formula, data=olist).fit()
fitted_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:          total_payment   R-squared:                       0.018
Model:                            OLS   Adj. R-squared:                  0.018
Method:                 Least Squares   F-statistic:                     28.25
Date:                Thu, 05 Dec 2019   Prob (F-statistic):               0.00
Time:                        11:44:05   Log-Likelihood:            -6.5944e+05
No. Observations:               96135   AIC:                         1.319e+06
Df Residuals:                   96070   BIC:                         1.320e+06
Df Model:                          64
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Intercept                 285.2386     26.379     10.813      0.000     233.535     336.942
C(customer_state)[T.AL]   -13.6071     28.704     -0.474      0.635     -69.867      42.653
C(customer_state)[T.AM]   -57.5860     32.606     -1.766      0.077    -121.494       6.322
C(customer_state)[T.AP]    -8.3091     38.540     -0.216      0.829     -83.848      67.230
C(customer_state)[T.BA]   -66.1396     26.598     -2.487      0.013    -118.271     -14.008
C(customer_state)[T.CE]   -41.1272     27.050     -1.520      0.128     -94.145      11.891
C(customer_state)[T.DF]   -81.2474     26.773     -3.035      0.002    -133.723     -28.772
C(customer_state)[T.ES]   -87.7504     26.801     -3.274      0.001    -140.279     -35.222
C(customer_state)[T.GO]   -72.8375     26.803     -2.718      0.007    -125.371     -20.304
C(customer_state)[T.MA]   -44.9014     27.650     -1.624      0.104     -99.095       9.293
C(customer_state)[T.MG]   -86.0380     26.380     -3.262      0.001    -137.742     -34.334
C(customer_state)[T.MS]   -52.7552     27.709     -1.904      0.057    -107.065       1.555
C(customer_state)[T.MT]   -38.9616     27.421     -1.421      0.155     -92.706      14.783
C(customer_state)[T.PA]   -24.4078     27.337     -0.893      0.372     -77.988      29.173
C(customer_state)[T.PB]    18.7097     28.172      0.664      0.507     -36.507      73.927
C(customer_state)[T.PE]   -51.4594     26.911     -1.912      0.056    -104.205       1.286
C(customer_state)[T.PI]   -29.2218     28.313     -1.032      0.302     -84.715      26.271
C(customer_state)[T.PR]   -85.9834     26.496     -3.245      0.001    -137.916     -34.051
C(customer_state)[T.RJ]   -82.4560     26.372     -3.127      0.002    -134.145     -30.767
C(customer_state)[T.RN]   -38.4302     28.345     -1.356      0.175     -93.986      17.126
C(customer_state)[T.RO]     1.4384     30.216      0.048      0.962     -57.785      60.662
C(customer_state)[T.RR]   -31.3170     43.285     -0.724      0.469    -116.155      53.522
C(customer_state)[T.RS]   -83.4591     26.481     -3.152      0.002    -135.361     -31.557
C(customer_state)[T.SC]   -76.5599     26.575     -2.881      0.004    -128.646     -24.474
C(customer_state)[T.SE]   -35.0925     29.100     -1.206      0.228     -92.128      21.943
C(customer_state)[T.SP]  -103.7033     26.315     -3.941      0.000    -155.280     -52.127
C(customer_state)[T.TO]   -28.4962     29.766     -0.957      0.338     -86.838      29.845
C(avg_score)[T.1.33]      203.5759    103.244      1.972      0.049       1.219     405.933
C(avg_score)[T.1.5]       106.1803     59.602      1.781      0.075     -10.639     223.000
C(avg_score)[T.1.67]      294.1165     81.585      3.605      0.000     134.210     454.023
C(avg_score)[T.1.75]      437.5274    230.680      1.897      0.058     -14.603     889.658
C(avg_score)[T.1.8]      1186.3974    230.680      5.143      0.000     734.267    1638.528
C(avg_score)[T.2.0]       -26.0162      4.681     -5.558      0.000     -35.190     -16.842
C(avg_score)[T.2.33]      213.2633     47.138      4.524      0.000     120.873     305.653
C(avg_score)[T.2.5]       152.8037     24.831      6.154      0.000     104.136     201.472
C(avg_score)[T.2.6]       -24.2226    230.680     -0.105      0.916    -476.353     427.908
C(avg_score)[T.2.67]      356.6026     87.214      4.089      0.000     185.664     527.541
C(avg_score)[T.2.78]      991.1247    230.675      4.297      0.000     539.004    1443.245
C(avg_score)[T.2.8]       809.4504    230.694      3.509      0.000     357.293    1261.608
C(avg_score)[T.3.0]       -41.4570      3.379    -12.271      0.000     -48.079     -34.835
C(avg_score)[T.3.1]       107.6613    230.705      0.467      0.641    -344.517     559.840
C(avg_score)[T.3.25]       99.4201    163.174      0.609      0.542    -220.399     419.239
C(avg_score)[T.3.33]      169.8081     76.923      2.208      0.027      19.040     320.576
C(avg_score)[T.3.4]       511.6192    230.793      2.217      0.027      59.268     963.970
C(avg_score)[T.3.5]       163.8899     19.350      8.470      0.000     125.965     201.815
C(avg_score)[T.3.52]      339.5347    230.675      1.472      0.141    -112.586     791.655
C(avg_score)[T.3.6]         7.7674    230.680      0.034      0.973    -444.363     459.898
C(avg_score)[T.3.67]      251.3760     33.028      7.611      0.000     186.642     316.110
C(avg_score)[T.3.75]      660.4618    230.730      2.862      0.004     208.233    1112.691
C(avg_score)[T.3.8]       674.7111    163.140      4.136      0.000     354.959     994.463
C(avg_score)[T.4.0]       -40.7453      2.772    -14.698      0.000     -46.179     -35.312
C(avg_score)[T.4.14]      183.2193    230.682      0.794      0.427    -268.915     635.354
C(avg_score)[T.4.2]      1008.2470    163.121      6.181      0.000     688.531    1327.963
C(avg_score)[T.4.25]      519.3113     94.198      5.513      0.000     334.685     703.938
C(avg_score)[T.4.33]      189.6808     37.002      5.126      0.000     117.158     262.204
C(avg_score)[T.4.4]       264.9270    163.121      1.624      0.104     -54.789     584.643
C(avg_score)[T.4.45]      -47.6753    230.675     -0.207      0.836    -499.796     404.445
C(avg_score)[T.4.5]       113.8431     14.033      8.113      0.000      86.339     141.347
C(avg_score)[T.4.6]       231.4247    230.675      1.003      0.316    -220.696     683.545
C(avg_score)[T.4.67]      144.2316     37.005      3.898      0.000      71.703     216.760
C(avg_score)[T.4.75]      284.8287     81.585      3.491      0.000     124.923     444.734
C(avg_score)[T.4.76]      746.0947    230.675      3.234      0.001     293.974    1198.215
C(avg_score)[T.4.8]       229.7147    163.121      1.408      0.159     -90.000     549.429
C(avg_score)[T.4.86]      815.7847    230.675      3.537      0.000     363.664    1267.905
C(avg_score)[T.5.0]       -36.5460      2.402    -15.216      0.000     -41.254     -31.838
==============================================================================
Omnibus:                   149376.980   Durbin-Watson:                   1.981
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        240256845.017
Skew:                           9.478   Prob(JB):                         0.00
Kurtosis:                     247.173   Cond. No.                         399.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""